version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: simulador_bancario
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    environment:
      DATABASE_URL: postgresql://postgres:sua_senha@db:5432/simulador_bancario
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
