name: CI - Bank Simulator API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: simulador_bancario_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env.test
        run: |
          echo "DATABASE_URL=postgresql://postgres:123456@localhost:5432/simulador_bancario_test" > .env.test

      - name: Gerar client Prisma
        run: npx prisma generate

      - name: Aplicar migrations
        run: npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Executar testes
        run: npm run test
